Answer.create!([
  {question_id: 244, text: "Lightsaber", pic_url: nil, ord: 1},
  {question_id: 244, text: "Helper monkey", pic_url: nil, ord: 2},
  {question_id: 245, text: "4 years for something I didn't do", pic_url: nil, ord: 1},
  {question_id: 245, text: "7 years for something I did do", pic_url: nil, ord: 2},
  {question_id: 246, text: "Without music", pic_url: nil, ord: 1},
  {question_id: 246, text: "Without TV", pic_url: nil, ord: 2},
  {question_id: 247, text: "be the world's best racquetball player?", pic_url: nil, ord: 1},
  {question_id: 247, text: "find $65 on the street?", pic_url: nil, ord: 2},
  {question_id: 248, text: "Always say what's on my mind", pic_url: nil, ord: 1},
  {question_id: 248, text: "Never speak again", pic_url: nil, ord: 2},
  {question_id: 249, text: "Yes", pic_url: nil, ord: 1},
  {question_id: 249, text: "No", pic_url: nil, ord: 2},
  {question_id: 249, text: "I'm undecided", pic_url: nil, ord: 3},
  {question_id: 250, text: "Yes", pic_url: nil, ord: 1},
  {question_id: 250, text: "No", pic_url: nil, ord: 2},
  {question_id: 250, text: "I'm undecided", pic_url: nil, ord: 3},
  {question_id: 251, text: "Definitely", pic_url: nil, ord: 1},
  {question_id: 251, text: "Not really", pic_url: nil, ord: 2},
  {question_id: 251, text: "Absolutely not", pic_url: nil, ord: 3},
  {question_id: 252, text: "Yes", pic_url: nil, ord: 1},
  {question_id: 252, text: "No", pic_url: nil, ord: 2},
  {question_id: 252, text: "I'm undecided", pic_url: nil, ord: 3},
  {question_id: 253, text: "True", pic_url: nil, ord: 1},
  {question_id: 253, text: "False", pic_url: nil, ord: 2},
  {question_id: 254, text: "magnesium", pic_url: nil, ord: 1},
  {question_id: 254, text: "bromine", pic_url: nil, ord: 2},
  {question_id: 254, text: "mercury", pic_url: nil, ord: 3},
  {question_id: 254, text: "gallium", pic_url: nil, ord: 4},
  {question_id: 255, text: "slightly acidic", pic_url: nil, ord: 1},
  {question_id: 255, text: "a strong acid", pic_url: nil, ord: 2},
  {question_id: 255, text: "neutral", pic_url: nil, ord: 3},
  {question_id: 255, text: "slightly basic", pic_url: nil, ord: 4},
  {question_id: 256, text: "tubulin", pic_url: nil, ord: 1},
  {question_id: 256, text: "albumin", pic_url: nil, ord: 2},
  {question_id: 256, text: "collagen", pic_url: nil, ord: 3},
  {question_id: 256, text: "keratin", pic_url: nil, ord: 4},
  {question_id: 257, text: "helium", pic_url: nil, ord: 1},
  {question_id: 257, text: "chlorine", pic_url: nil, ord: 2},
  {question_id: 257, text: "krypton", pic_url: nil, ord: 3},
  {question_id: 257, text: "argon", pic_url: nil, ord: 4},
  {question_id: 258, text: "protium", pic_url: nil, ord: 1},
  {question_id: 258, text: "deuterium", pic_url: nil, ord: 2},
  {question_id: 258, text: "tritium", pic_url: nil, ord: 3},
  {question_id: 259, text: "Mendel", pic_url: nil, ord: 1},
  {question_id: 259, text: "Mendeleev", pic_url: nil, ord: 2},
  {question_id: 259, text: "Lavoisier", pic_url: nil, ord: 3},
  {question_id: 260, text: "your brain", pic_url: nil, ord: 1},
  {question_id: 260, text: "your muscles", pic_url: nil, ord: 2},
  {question_id: 260, text: "your bones", pic_url: nil, ord: 3},
  {question_id: 260, text: "your blood", pic_url: nil, ord: 4},
  {question_id: 261, text: "True", pic_url: nil, ord: 1},
  {question_id: 261, text: "False", pic_url: nil, ord: 2},
  {question_id: 262, text: "cheetah", pic_url: nil, ord: 1},
  {question_id: 262, text: "lion", pic_url: nil, ord: 2},
  {question_id: 262, text: "man", pic_url: nil, ord: 3},
  {question_id: 262, text: "jaguar", pic_url: nil, ord: 4},
  {question_id: 263, text: "copper", pic_url: nil, ord: 1},
  {question_id: 263, text: "iron", pic_url: nil, ord: 2},
  {question_id: 263, text: "magnesium", pic_url: nil, ord: 3},
  {question_id: 263, text: "calcium", pic_url: nil, ord: 4},
  {question_id: 264, text: "West Coast", pic_url: nil, ord: 1},
  {question_id: 264, text: "East Coast", pic_url: nil, ord: 2},
  {question_id: 264, text: "Midwest", pic_url: nil, ord: 3},
  {question_id: 264, text: "South", pic_url: nil, ord: 4},
  {question_id: 265, text: "first-year teacher", pic_url: nil, ord: 1},
  {question_id: 265, text: "second-year teacher", pic_url: nil, ord: 2},
  {question_id: 265, text: "teacher of three years or more", pic_url: nil, ord: 3},
  {question_id: 265, text: "not a teacher", pic_url: nil, ord: 4},
  {question_id: 267, text: "25%", pic_url: nil, ord: 1},
  {question_id: 267, text: "50%", pic_url: nil, ord: 2},
  {question_id: 267, text: "60%", pic_url: nil, ord: 3},
  {question_id: 267, text: "25%", pic_url: nil, ord: 4},
  {question_id: 268, text: "That it's entirely single-page", pic_url: nil, ord: 1},
  {question_id: 268, text: "The snazzy landing page", pic_url: nil, ord: 2},
  {question_id: 268, text: "The great UI for editing surveys", pic_url: nil, ord: 3},
  {question_id: 268, text: "Survey navigation with prev/next buttons", pic_url: nil, ord: 4},
  {question_id: 269, text: "JavaScript, jQuery, client MV* systems", pic_url: nil, ord: 1},
  {question_id: 269, text: "CSS", pic_url: nil, ord: 2},
  {question_id: 269, text: "SQL", pic_url: nil, ord: 3},
  {question_id: 269, text: "Ruby on Rails", pic_url: nil, ord: 4},
  {question_id: 243, text: "zero", pic_url: nil, ord: 1},
  {question_id: 243, text: "fewer than 10", pic_url: nil, ord: 2},
  {question_id: 243, text: "fewer than 20", pic_url: nil, ord: 3},
  {question_id: 243, text: "more than 21", pic_url: nil, ord: 4},
  {question_id: 266, text: "Inspiration", pic_url: nil, ord: 1},
  {question_id: 266, text: "Teaching strategies", pic_url: nil, ord: 2},
  {question_id: 266, text: "Networking/ collaboration", pic_url: nil, ord: 3},
  {question_id: 266, text: "Free food", pic_url: nil, ord: 4}
])
Question.create!([
  {user_id: 38, survey_id: nil, chart_type: nil, pic_url: nil, title: "How many total responses does this question have right now?", ord: nil},
  {user_id: 38, survey_id: 210, chart_type: nil, pic_url: nil, title: "Would you rather have a lightsaber or helper monkey?", ord: 1},
  {user_id: 38, survey_id: 210, chart_type: nil, pic_url: nil, title: "Would you rather spend 4 years in jail for something you didn't do or spend 7 years in jail for something you did do?", ord: 2},
  {user_id: 38, survey_id: 210, chart_type: nil, pic_url: nil, title: "Would you rather always say what's on your mind or never speak again?", ord: 4},
  {user_id: 38, survey_id: 210, chart_type: nil, pic_url: nil, title: "Would you rather live without music or without TV?", ord: 5},
  {user_id: 38, survey_id: 210, chart_type: nil, pic_url: nil, title: "Would you rather ...", ord: 3},
  {user_id: 38, survey_id: 211, chart_type: nil, pic_url: nil, title: "Does God exist?", ord: 1},
  {user_id: 38, survey_id: 211, chart_type: nil, pic_url: nil, title: "Should marijuana be legal for recreational use?", ord: 3},
  {user_id: 38, survey_id: 211, chart_type: nil, pic_url: nil, title: "Is it ethical to eat meat?", ord: 2},
  {user_id: 38, survey_id: 211, chart_type: nil, pic_url: nil, title: "Should people of the same sex be allowed to marry each other?", ord: 4},
  {user_id: 38, survey_id: 212, chart_type: nil, pic_url: nil, title: "If you allow the ice in a full glass of ice water to melt, the glass will overflow.", ord: 1},
  {user_id: 38, survey_id: 212, chart_type: nil, pic_url: nil, title: "All of the following elements are liquid at or near room temperature except:", ord: 2},
  {user_id: 38, survey_id: 212, chart_type: nil, pic_url: nil, title: "Milk is...", ord: 3},
  {user_id: 38, survey_id: 212, chart_type: nil, pic_url: nil, title: "The most abundant protein in the human body is:", ord: 4},
  {user_id: 38, survey_id: 212, chart_type: nil, pic_url: nil, title: "Which of these elements is not a noble gas?", ord: 5},
  {user_id: 38, survey_id: 213, chart_type: nil, pic_url: nil, title: "The most common isotope of hydrogen is...", ord: 1},
  {user_id: 38, survey_id: 213, chart_type: nil, pic_url: nil, title: "The modern periodic table was invented by...", ord: 2},
  {user_id: 38, survey_id: 213, chart_type: nil, pic_url: nil, title: "Most of the iron in your body is found where?", ord: 3},
  {user_id: 38, survey_id: 214, chart_type: nil, pic_url: nil, title: "The tail of a comet always points toward the Sun.", ord: 1},
  {user_id: 38, survey_id: 214, chart_type: nil, pic_url: nil, title: "The fastest-running terrestrial animal is:", ord: 2},
  {user_id: 38, survey_id: 214, chart_type: nil, pic_url: nil, title: "Chlorophyll is a naturally occurring chelate compound in which central metal is", ord: 3},
  {user_id: 38, survey_id: 215, chart_type: nil, pic_url: nil, title: "Which part of the country do you teach in?", ord: 1},
  {user_id: 38, survey_id: 215, chart_type: nil, pic_url: nil, title: "I am a...", ord: 2},
  {user_id: 38, survey_id: 215, chart_type: nil, pic_url: nil, title: "What is the most important thing that you are hoping to get out of this conference?", ord: 3},
  {user_id: 38, survey_id: nil, chart_type: nil, pic_url: nil, title: "If you choose an answer to this question at random, what is the chance you will be correct?", ord: nil},
  {user_id: 38, survey_id: nil, chart_type: nil, pic_url: nil, title: "What is the best thing about this web app?", ord: nil},
  {user_id: 38, survey_id: nil, chart_type: nil, pic_url: nil, title: "What is your favorite web-related technology/language?", ord: nil}
])
Response.create!([
  {answer_id: 539, answerer_id: "djr2dd2ac"},
  {answer_id: 623, answerer_id: "djr2dd2ac"},
  {answer_id: 626, answerer_id: "djr2dd2ac"},
  {answer_id: 626, answerer_id: "djr2dd2ac"},
  {answer_id: 626, answerer_id: "djr2dd2ac"},
  {answer_id: 624, answerer_id: "djr2dd2ac"},
  {answer_id: 625, answerer_id: "djr2dd2ac"},
  {answer_id: 625, answerer_id: "djr2dd2ac"},
  {answer_id: 623, answerer_id: "djr2dd2ac"},
  {answer_id: 623, answerer_id: "djr2dd2ac"},
  {answer_id: 623, answerer_id: "djr2dd2ac"},
  {answer_id: 623, answerer_id: "djr2dd2ac"},
  {answer_id: 626, answerer_id: "djr2dd2ac"},
  {answer_id: 626, answerer_id: "djr2dd2ac"},
  {answer_id: 626, answerer_id: "djr2dd2ac"},
  {answer_id: 626, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 565, answerer_id: "djr2dd2ac"},
  {answer_id: 565, answerer_id: "djr2dd2ac"},
  {answer_id: 565, answerer_id: "djr2dd2ac"},
  {answer_id: 565, answerer_id: "djr2dd2ac"},
  {answer_id: 565, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 566, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 567, answerer_id: "djr2dd2ac"},
  {answer_id: 568, answerer_id: "djr2dd2ac"},
  {answer_id: 568, answerer_id: "djr2dd2ac"},
  {answer_id: 568, answerer_id: "djr2dd2ac"},
  {answer_id: 568, answerer_id: "djr2dd2ac"},
  {answer_id: 568, answerer_id: "djr2dd2ac"},
  {answer_id: 568, answerer_id: "djr2dd2ac"},
  {answer_id: 568, answerer_id: "djr2dd2ac"},
  {answer_id: 569, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 570, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 571, answerer_id: "djr2dd2ac"},
  {answer_id: 572, answerer_id: "djr2dd2ac"},
  {answer_id: 572, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 574, answerer_id: "djr2dd2ac"},
  {answer_id: 574, answerer_id: "djr2dd2ac"},
  {answer_id: 574, answerer_id: "djr2dd2ac"},
  {answer_id: 574, answerer_id: "djr2dd2ac"},
  {answer_id: 574, answerer_id: "djr2dd2ac"},
  {answer_id: 574, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 573, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 577, answerer_id: "djr2dd2ac"},
  {answer_id: 575, answerer_id: "djr2dd2ac"},
  {answer_id: 576, answerer_id: "djr2dd2ac"},
  {answer_id: 576, answerer_id: "djr2dd2ac"},
  {answer_id: 576, answerer_id: "djr2dd2ac"},
  {answer_id: 576, answerer_id: "djr2dd2ac"},
  {answer_id: 576, answerer_id: "djr2dd2ac"},
  {answer_id: 576, answerer_id: "djr2dd2ac"},
  {answer_id: 578, answerer_id: "djr2dd2ac"},
  {answer_id: 578, answerer_id: "djr2dd2ac"},
  {answer_id: 579, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 580, answerer_id: "djr2dd2ac"},
  {answer_id: 581, answerer_id: "djr2dd2ac"},
  {answer_id: 581, answerer_id: "djr2dd2ac"},
  {answer_id: 581, answerer_id: "djr2dd2ac"},
  {answer_id: 582, answerer_id: "djr2dd2ac"},
  {answer_id: 582, answerer_id: "djr2dd2ac"},
  {answer_id: 582, answerer_id: "djr2dd2ac"},
  {answer_id: 582, answerer_id: "djr2dd2ac"},
  {answer_id: 582, answerer_id: "djr2dd2ac"},
  {answer_id: 582, answerer_id: "djr2dd2ac"},
  {answer_id: 582, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 620, answerer_id: "djr2dd2ac"},
  {answer_id: 620, answerer_id: "djr2dd2ac"},
  {answer_id: 620, answerer_id: "djr2dd2ac"},
  {answer_id: 620, answerer_id: "djr2dd2ac"},
  {answer_id: 620, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 620, answerer_id: "djr2dd2ac"},
  {answer_id: 620, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 621, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 619, answerer_id: "djr2dd2ac"},
  {answer_id: 622, answerer_id: "djr2dd2ac"},
  {answer_id: 627, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 605, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 606, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 604, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 603, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 609, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 610, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 608, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 607, answerer_id: "djr2dd2ac"},
  {answer_id: 610, answerer_id: "djr2dd2ac"},
  {answer_id: 610, answerer_id: "djr2dd2ac"},
  {answer_id: 610, answerer_id: "djr2dd2ac"},
  {answer_id: 610, answerer_id: "djr2dd2ac"},
  {answer_id: 610, answerer_id: "djr2dd2ac"},
  {answer_id: 631, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 631, answerer_id: "djr2dd2ac"},
  {answer_id: 631, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 634, answerer_id: "djr2dd2ac"},
  {answer_id: 634, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 631, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 634, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 631, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 634, answerer_id: "djr2dd2ac"},
  {answer_id: 634, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 633, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 632, answerer_id: "djr2dd2ac"},
  {answer_id: 631, answerer_id: "djr2dd2ac"},
  {answer_id: 631, answerer_id: "djr2dd2ac"},
  {answer_id: 631, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 555, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 554, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 553, answerer_id: "djr2dd2ac"},
  {answer_id: 560, answerer_id: "djr2dd2ac"},
  {answer_id: 559, answerer_id: "djr2dd2ac"},
  {answer_id: 560, answerer_id: "djr2dd2ac"},
  {answer_id: 561, answerer_id: "djr2dd2ac"},
  {answer_id: 560, answerer_id: "djr2dd2ac"},
  {answer_id: 559, answerer_id: "djr2dd2ac"},
  {answer_id: 559, answerer_id: "djr2dd2ac"},
  {answer_id: 560, answerer_id: "djr2dd2ac"},
  {answer_id: 559, answerer_id: "djr2dd2ac"},
  {answer_id: 559, answerer_id: "djr2dd2ac"},
  {answer_id: 559, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 558, answerer_id: "djr2dd2ac"},
  {answer_id: 558, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 558, answerer_id: "djr2dd2ac"},
  {answer_id: 558, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 558, answerer_id: "djr2dd2ac"},
  {answer_id: 558, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 558, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 556, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 557, answerer_id: "djr2dd2ac"},
  {answer_id: 562, answerer_id: "djr2dd2ac"},
  {answer_id: 562, answerer_id: "djr2dd2ac"},
  {answer_id: 564, answerer_id: "djr2dd2ac"},
  {answer_id: 564, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 562, answerer_id: "djr2dd2ac"},
  {answer_id: 564, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 562, answerer_id: "djr2dd2ac"},
  {answer_id: 564, answerer_id: "djr2dd2ac"},
  {answer_id: 564, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 562, answerer_id: "djr2dd2ac"},
  {answer_id: 562, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 564, answerer_id: "djr2dd2ac"},
  {answer_id: 564, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 562, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 564, answerer_id: "djr2dd2ac"},
  {answer_id: 564, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 562, answerer_id: "djr2dd2ac"},
  {answer_id: 562, answerer_id: "djr2dd2ac"},
  {answer_id: 563, answerer_id: "djr2dd2ac"},
  {answer_id: 543, answerer_id: "djr2dd2ac"},
  {answer_id: 543, answerer_id: "djr2dd2ac"},
  {answer_id: 543, answerer_id: "djr2dd2ac"},
  {answer_id: 543, answerer_id: "djr2dd2ac"},
  {answer_id: 543, answerer_id: "djr2dd2ac"},
  {answer_id: 543, answerer_id: "djr2dd2ac"},
  {answer_id: 544, answerer_id: "djr2dd2ac"},
  {answer_id: 544, answerer_id: "djr2dd2ac"},
  {answer_id: 544, answerer_id: "djr2dd2ac"},
  {answer_id: 544, answerer_id: "djr2dd2ac"},
  {answer_id: 544, answerer_id: "djr2dd2ac"},
  {answer_id: 544, answerer_id: "djr2dd2ac"},
  {answer_id: 543, answerer_id: "djr2dd2ac"},
  {answer_id: 543, answerer_id: "djr2dd2ac"},
  {answer_id: 544, answerer_id: "djr2dd2ac"},
  {answer_id: 543, answerer_id: "djr2dd2ac"},
  {answer_id: 545, answerer_id: "djr2dd2ac"},
  {answer_id: 545, answerer_id: "djr2dd2ac"},
  {answer_id: 545, answerer_id: "djr2dd2ac"},
  {answer_id: 545, answerer_id: "djr2dd2ac"},
  {answer_id: 545, answerer_id: "djr2dd2ac"},
  {answer_id: 546, answerer_id: "djr2dd2ac"},
  {answer_id: 546, answerer_id: "djr2dd2ac"},
  {answer_id: 546, answerer_id: "djr2dd2ac"},
  {answer_id: 546, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 550, answerer_id: "djr2dd2ac"},
  {answer_id: 549, answerer_id: "djr2dd2ac"},
  {answer_id: 549, answerer_id: "djr2dd2ac"},
  {answer_id: 549, answerer_id: "djr2dd2ac"},
  {answer_id: 549, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 551, answerer_id: "djr2dd2ac"},
  {answer_id: 552, answerer_id: "djr2dd2ac"},
  {answer_id: 552, answerer_id: "djr2dd2ac"},
  {answer_id: 552, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 547, answerer_id: "djr2dd2ac"},
  {answer_id: 547, answerer_id: "djr2dd2ac"},
  {answer_id: 547, answerer_id: "djr2dd2ac"},
  {answer_id: 547, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 548, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 583, answerer_id: "djr2dd2ac"},
  {answer_id: 584, answerer_id: "djr2dd2ac"},
  {answer_id: 584, answerer_id: "djr2dd2ac"},
  {answer_id: 584, answerer_id: "djr2dd2ac"},
  {answer_id: 584, answerer_id: "djr2dd2ac"},
  {answer_id: 584, answerer_id: "djr2dd2ac"},
  {answer_id: 585, answerer_id: "djr2dd2ac"},
  {answer_id: 585, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 587, answerer_id: "djr2dd2ac"},
  {answer_id: 586, answerer_id: "djr2dd2ac"},
  {answer_id: 586, answerer_id: "djr2dd2ac"},
  {answer_id: 586, answerer_id: "djr2dd2ac"},
  {answer_id: 586, answerer_id: "djr2dd2ac"},
  {answer_id: 586, answerer_id: "djr2dd2ac"},
  {answer_id: 586, answerer_id: "djr2dd2ac"},
  {answer_id: 586, answerer_id: "djr2dd2ac"},
  {answer_id: 588, answerer_id: "djr2dd2ac"},
  {answer_id: 588, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 592, answerer_id: "djr2dd2ac"},
  {answer_id: 589, answerer_id: "djr2dd2ac"},
  {answer_id: 589, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 590, answerer_id: "djr2dd2ac"},
  {answer_id: 591, answerer_id: "djr2dd2ac"},
  {answer_id: 591, answerer_id: "djr2dd2ac"},
  {answer_id: 591, answerer_id: "djr2dd2ac"},
  {answer_id: 591, answerer_id: "djr2dd2ac"},
  {answer_id: 591, answerer_id: "djr2dd2ac"}
])
Survey.create!([
  {user_id: 38, title: "Would You Rather...", default_num_questions: 2},
  {user_id: 38, title: "Controversial Questions", default_num_questions: 2},
  {user_id: 38, title: "End-Of-Day Comprehension Check (Dec 5)", default_num_questions: 2},
  {user_id: 38, title: "End-Of-Day Comprehension Check (Dec 6)", default_num_questions: 2},
  {user_id: 38, title: "End-Of-Day Comprehension Check (Dec 7)", default_num_questions: 2},
  {user_id: 38, title: "San Diego Teach For America Keynote Presentation", default_num_questions: 2}
])
User.create!([
  {email: "demo@user.net", session_token: "zfHl1kPqekr3i_U86i0OHw", password_digest: "$2a$10$e.Rd/3Y5tINvQQxWD4kFPe.H/tEUyv2UNoGldf0HPYwt16IyX9bm2"}
])
