User.create!([
  {email: "demo@user.net", session_token: "A2KGRVzxLBn84Z05cdmtRw", password_digest: "$2a$10$e.Rd/3Y5tINvQQxWD4kFPe.H/tEUyv2UNoGldf0HPYwt16IyX9bm2"}
])

Survey.create!([
  {user_id: 1, title: "Would You Rather...", default_num_questions: 2},
  {user_id: 1, title: "Controversial Questions", default_num_questions: 2},
  {user_id: 1, title: "End-Of-Day Comprehension Check (Dec 5)", default_num_questions: 2},
  {user_id: 1, title: "End-Of-Day Comprehension Check (Dec 6)", default_num_questions: 2},
  {user_id: 1, title: "End-Of-Day Comprehension Check (Dec 7)", default_num_questions: 2},
  {user_id: 1, title: "San Diego Teach For America Keynote Presentation", default_num_questions: 2}
])

Question.create!([
  {user_id: 1, survey_id: 1, chart_type: nil, pic_url: nil, title: "Would you rather have a lightsaber or helper monkey?", ord: 1},
  {user_id: 1, survey_id: 1, chart_type: nil, pic_url: nil, title: "Would you rather spend 4 years in jail for something you didn't do or spend 7 years in jail for something you did do?", ord: 2},
  {user_id: 1, survey_id: 1, chart_type: nil, pic_url: nil, title: "Would you rather live without music or without TV?", ord: 5},
  {user_id: 1, survey_id: 1, chart_type: nil, pic_url: nil, title: "Would you rather ...", ord: 3},
  {user_id: 1, survey_id: 1, chart_type: nil, pic_url: nil, title: "Would you rather always say what's on your mind or never speak again?", ord: 4},
  {user_id: 1, survey_id: 2, chart_type: nil, pic_url: nil, title: "Does God exist?", ord: 1},
  {user_id: 1, survey_id: 2, chart_type: nil, pic_url: nil, title: "Should marijuana be legal for recreational use?", ord: 3},
  {user_id: 1, survey_id: 2, chart_type: nil, pic_url: nil, title: "Is it ethical to eat meat?", ord: 2},
  {user_id: 1, survey_id: 2, chart_type: nil, pic_url: nil, title: "Should people of the same sex be allowed to marry each other?", ord: 4},
  {user_id: 1, survey_id: 3, chart_type: nil, pic_url: nil, title: "If you allow the ice in a full glass of ice water to melt, the glass will overflow.", ord: 1},
  {user_id: 1, survey_id: 3, chart_type: nil, pic_url: nil, title: "All of the following elements are liquid at or near room temperature except:", ord: 2},
  {user_id: 1, survey_id: 3, chart_type: nil, pic_url: nil, title: "Milk is...", ord: 3},
  {user_id: 1, survey_id: 3, chart_type: nil, pic_url: nil, title: "The most abundant protein in the human body is:", ord: 4},
  {user_id: 1, survey_id: 3, chart_type: nil, pic_url: nil, title: "Which of these elements is not a noble gas?", ord: 5},
  {user_id: 1, survey_id: 4, chart_type: nil, pic_url: nil, title: "The most common isotope of hydrogen is...", ord: 1},
  {user_id: 1, survey_id: 4, chart_type: nil, pic_url: nil, title: "The modern periodic table was invented by...", ord: 2},
  {user_id: 1, survey_id: 4, chart_type: nil, pic_url: nil, title: "Most of the iron in your body is found where?", ord: 3},
  {user_id: 1, survey_id: 5, chart_type: nil, pic_url: nil, title: "The tail of a comet always points toward the Sun.", ord: 1},
  {user_id: 1, survey_id: 5, chart_type: nil, pic_url: nil, title: "The fastest-running terrestrial animal is:", ord: 2},
  {user_id: 1, survey_id: 5, chart_type: nil, pic_url: nil, title: "Chlorophyll is a naturally occurring chelate compound in which central metal is", ord: 3},
  {user_id: 1, survey_id: 6, chart_type: nil, pic_url: nil, title: "Which part of the country do you teach in?", ord: 1},
  {user_id: 1, survey_id: 6, chart_type: nil, pic_url: nil, title: "I am a...", ord: 2},
  {user_id: 1, survey_id: 6, chart_type: nil, pic_url: nil, title: "What is the most important thing that you are hoping to get out of this conference?", ord: 3},
  {user_id: 1, survey_id: nil, chart_type: nil, pic_url: nil, title: "If you choose an answer to this question at random, what is the chance you will be correct?", ord: nil},
  {user_id: 1, survey_id: nil, chart_type: nil, pic_url: nil, title: "What is the best thing about this web app?", ord: nil},
  {user_id: 1, survey_id: nil, chart_type: nil, pic_url: nil, title: "How many total responses does this question have right now?", ord: nil},
  {user_id: 1, survey_id: nil, chart_type: nil, pic_url: nil, title: "What is your favorite web-related technology/language?", ord: nil}
])

Answer.create!([
  {question_id: 1, text: "Lightsaber", pic_url: nil, ord: 1},
  {question_id: 1, text: "Helper monkey", pic_url: nil, ord: 2},
  {question_id: 2, text: "4 years for something I didn't do", pic_url: nil, ord: 1},
  {question_id: 2, text: "7 years for something I did do", pic_url: nil, ord: 2},
  {question_id: 3, text: "Without music", pic_url: nil, ord: 1},
  {question_id: 3, text: "Without TV", pic_url: nil, ord: 2},
  {question_id: 4, text: "be the world's best racquetball player?", pic_url: nil, ord: 1},
  {question_id: 4, text: "find $65 on the street?", pic_url: nil, ord: 2},
  {question_id: 5, text: "Always say what's on my mind", pic_url: nil, ord: 1},
  {question_id: 5, text: "Never speak again", pic_url: nil, ord: 2},
  {question_id: 6, text: "Yes", pic_url: nil, ord: 1},
  {question_id: 6, text: "No", pic_url: nil, ord: 2},
  {question_id: 6, text: "I'm undecided", pic_url: nil, ord: 3},
  {question_id: 7, text: "Yes", pic_url: nil, ord: 1},
  {question_id: 7, text: "No", pic_url: nil, ord: 2},
  {question_id: 7, text: "I'm undecided", pic_url: nil, ord: 3},
  {question_id: 8, text: "Definitely", pic_url: nil, ord: 1},
  {question_id: 8, text: "Not really", pic_url: nil, ord: 2},
  {question_id: 8, text: "Absolutely not", pic_url: nil, ord: 3},
  {question_id: 9, text: "Yes", pic_url: nil, ord: 1},
  {question_id: 9, text: "No", pic_url: nil, ord: 2},
  {question_id: 9, text: "I'm undecided", pic_url: nil, ord: 3},
  {question_id: 10, text: "True", pic_url: nil, ord: 1},
  {question_id: 10, text: "False", pic_url: nil, ord: 2},
  {question_id: 11, text: "magnesium", pic_url: nil, ord: 1},
  {question_id: 11, text: "bromine", pic_url: nil, ord: 2},
  {question_id: 11, text: "mercury", pic_url: nil, ord: 3},
  {question_id: 11, text: "gallium", pic_url: nil, ord: 4},
  {question_id: 12, text: "slightly acidic", pic_url: nil, ord: 1},
  {question_id: 12, text: "a strong acid", pic_url: nil, ord: 2},
  {question_id: 12, text: "neutral", pic_url: nil, ord: 3},
  {question_id: 12, text: "slightly basic", pic_url: nil, ord: 4},
  {question_id: 13, text: "tubulin", pic_url: nil, ord: 1},
  {question_id: 13, text: "albumin", pic_url: nil, ord: 2},
  {question_id: 13, text: "collagen", pic_url: nil, ord: 3},
  {question_id: 13, text: "keratin", pic_url: nil, ord: 4},
  {question_id: 14, text: "helium", pic_url: nil, ord: 1},
  {question_id: 14, text: "chlorine", pic_url: nil, ord: 2},
  {question_id: 14, text: "krypton", pic_url: nil, ord: 3},
  {question_id: 14, text: "argon", pic_url: nil, ord: 4},
  {question_id: 15, text: "protium", pic_url: nil, ord: 1},
  {question_id: 15, text: "deuterium", pic_url: nil, ord: 2},
  {question_id: 15, text: "tritium", pic_url: nil, ord: 3},
  {question_id: 16, text: "Mendel", pic_url: nil, ord: 1},
  {question_id: 16, text: "Mendeleev", pic_url: nil, ord: 2},
  {question_id: 16, text: "Lavoisier", pic_url: nil, ord: 3},
  {question_id: 17, text: "your brain", pic_url: nil, ord: 1},
  {question_id: 17, text: "your muscles", pic_url: nil, ord: 2},
  {question_id: 17, text: "your bones", pic_url: nil, ord: 3},
  {question_id: 17, text: "your blood", pic_url: nil, ord: 4},
  {question_id: 18, text: "True", pic_url: nil, ord: 1},
  {question_id: 18, text: "False", pic_url: nil, ord: 2},
  {question_id: 19, text: "cheetah", pic_url: nil, ord: 1},
  {question_id: 19, text: "lion", pic_url: nil, ord: 2},
  {question_id: 19, text: "man", pic_url: nil, ord: 3},
  {question_id: 19, text: "jaguar", pic_url: nil, ord: 4},
  {question_id: 20, text: "copper", pic_url: nil, ord: 1},
  {question_id: 20, text: "iron", pic_url: nil, ord: 2},
  {question_id: 20, text: "magnesium", pic_url: nil, ord: 3},
  {question_id: 20, text: "calcium", pic_url: nil, ord: 4},
  {question_id: 21, text: "West Coast", pic_url: nil, ord: 1},
  {question_id: 21, text: "East Coast", pic_url: nil, ord: 2},
  {question_id: 21, text: "Midwest", pic_url: nil, ord: 3},
  {question_id: 21, text: "South", pic_url: nil, ord: 4},
  {question_id: 22, text: "first-year teacher", pic_url: nil, ord: 1},
  {question_id: 22, text: "second-year teacher", pic_url: nil, ord: 2},
  {question_id: 22, text: "teacher of three years or more", pic_url: nil, ord: 3},
  {question_id: 22, text: "not a teacher", pic_url: nil, ord: 4},
  {question_id: 23, text: "Inspiration", pic_url: nil, ord: 1},
  {question_id: 23, text: "Teaching strategies", pic_url: nil, ord: 2},
  {question_id: 23, text: "Networking/ collaboration", pic_url: nil, ord: 3},
  {question_id: 23, text: "Free food", pic_url: nil, ord: 4},
  {question_id: 24, text: "25%", pic_url: nil, ord: 1},
  {question_id: 24, text: "50%", pic_url: nil, ord: 2},
  {question_id: 24, text: "60%", pic_url: nil, ord: 3},
  {question_id: 24, text: "25%", pic_url: nil, ord: 4},
  {question_id: 25, text: "That it's entirely single-page", pic_url: nil, ord: 1},
  {question_id: 25, text: "The snazzy landing page", pic_url: nil, ord: 2},
  {question_id: 25, text: "The great UI for editing surveys", pic_url: nil, ord: 3},
  {question_id: 25, text: "Survey navigation with prev/next buttons", pic_url: nil, ord: 4},
  {question_id: 26, text: "zero", pic_url: nil, ord: 1},
  {question_id: 26, text: "fewer than 10", pic_url: nil, ord: 2},
  {question_id: 26, text: "fewer than 20", pic_url: nil, ord: 3},
  {question_id: 26, text: "more than 21", pic_url: nil, ord: 4},
  {question_id: 27, text: "JavaScript, jQuery, client MV* systems", pic_url: nil, ord: 1},
  {question_id: 27, text: "CSS", pic_url: nil, ord: 2},
  {question_id: 27, text: "SQL", pic_url: nil, ord: 3},
  {question_id: 27, text: "Ruby on Rails", pic_url: nil, ord: 4}
])

Response.create!([
  {answer_id: 85},
  {answer_id: 87},
  {answer_id: 86},
  {answer_id: 85},
  {answer_id: 88},
  {answer_id: 85},
  {answer_id: 88},
  {answer_id: 85},
  {answer_id: 87},
  {answer_id: 85},
  {answer_id: 85},
  {answer_id: 85},
  {answer_id: 87},
  {answer_id: 88},
  {answer_id: 85},
  {answer_id: 86},
  {answer_id: 87},
  {answer_id: 81},
  {answer_id: 80},
  {answer_id: 79},
  {answer_id: 77},
  {answer_id: 77},
  {answer_id: 78},
  {answer_id: 78},
  {answer_id: 79},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 79},
  {answer_id: 79},
  {answer_id: 79},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 78},
  {answer_id: 78},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 80},
  {answer_id: 77},
  {answer_id: 78},
  {answer_id: 78},
  {answer_id: 24},
  {answer_id: 24},
  {answer_id: 24},
  {answer_id: 24},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 24},
  {answer_id: 24},
  {answer_id: 23},
  {answer_id: 23},
  {answer_id: 24},
  {answer_id: 23},
  {answer_id: 28},
  {answer_id: 28},
  {answer_id: 27},
  {answer_id: 26},
  {answer_id: 25},
  {answer_id: 25},
  {answer_id: 26},
  {answer_id: 27},
  {answer_id: 28},
  {answer_id: 28},
  {answer_id: 27},
  {answer_id: 25},
  {answer_id: 25},
  {answer_id: 26},
  {answer_id: 27},
  {answer_id: 28},
  {answer_id: 29},
  {answer_id: 29},
  {answer_id: 29},
  {answer_id: 32},
  {answer_id: 30},
  {answer_id: 30},
  {answer_id: 31},
  {answer_id: 29},
  {answer_id: 29},
  {answer_id: 36},
  {answer_id: 36},
  {answer_id: 35},
  {answer_id: 34},
  {answer_id: 33},
  {answer_id: 33},
  {answer_id: 35},
  {answer_id: 36},
  {answer_id: 35},
  {answer_id: 35},
  {answer_id: 35},
  {answer_id: 35},
  {answer_id: 35},
  {answer_id: 35},
  {answer_id: 34},
  {answer_id: 33},
  {answer_id: 33},
  {answer_id: 33},
  {answer_id: 40},
  {answer_id: 40},
  {answer_id: 38},
  {answer_id: 38},
  {answer_id: 37},
  {answer_id: 37},
  {answer_id: 38},
  {answer_id: 39},
  {answer_id: 39},
  {answer_id: 40},
  {answer_id: 40},
  {answer_id: 39},
  {answer_id: 39},
  {answer_id: 38},
  {answer_id: 38},
  {answer_id: 37},
  {answer_id: 37},
  {answer_id: 38},
  {answer_id: 39},
  {answer_id: 40},
  {answer_id: 38},
  {answer_id: 38},
  {answer_id: 38},
  {answer_id: 38},
  {answer_id: 38},
  {answer_id: 38},
  {answer_id: 40},
  {answer_id: 40},
  {answer_id: 63},
  {answer_id: 64},
  {answer_id: 64},
  {answer_id: 63},
  {answer_id: 62},
  {answer_id: 61},
  {answer_id: 61},
  {answer_id: 61},
  {answer_id: 61},
  {answer_id: 62},
  {answer_id: 62},
  {answer_id: 63},
  {answer_id: 64},
  {answer_id: 64},
  {answer_id: 63},
  {answer_id: 62},
  {answer_id: 61},
  {answer_id: 61},
  {answer_id: 61},
  {answer_id: 62},
  {answer_id: 61},
  {answer_id: 61},
  {answer_id: 62},
  {answer_id: 62},
  {answer_id: 62},
  {answer_id: 61},
  {answer_id: 68},
  {answer_id: 68},
  {answer_id: 67},
  {answer_id: 67},
  {answer_id: 66},
  {answer_id: 66},
  {answer_id: 65},
  {answer_id: 65},
  {answer_id: 65},
  {answer_id: 66},
  {answer_id: 67},
  {answer_id: 67},
  {answer_id: 67},
  {answer_id: 68},
  {answer_id: 68},
  {answer_id: 67},
  {answer_id: 66},
  {answer_id: 65},
  {answer_id: 65},
  {answer_id: 65},
  {answer_id: 65},
  {answer_id: 65},
  {answer_id: 65},
  {answer_id: 66},
  {answer_id: 66},
  {answer_id: 66},
  {answer_id: 65},
  {answer_id: 65},
  {answer_id: 68},
  {answer_id: 68},
  {answer_id: 68},
  {answer_id: 68},
  {answer_id: 68},
  {answer_id: 70},
  {answer_id: 70},
  {answer_id: 71},
  {answer_id: 71},
  {answer_id: 72},
  {answer_id: 72},
  {answer_id: 69},
  {answer_id: 69},
  {answer_id: 70},
  {answer_id: 70},
  {answer_id: 71},
  {answer_id: 71},
  {answer_id: 72},
  {answer_id: 71},
  {answer_id: 69},
  {answer_id: 69},
  {answer_id: 70},
  {answer_id: 70},
  {answer_id: 71},
  {answer_id: 71},
  {answer_id: 72},
  {answer_id: 72},
  {answer_id: 71},
  {answer_id: 71},
  {answer_id: 69},
  {answer_id: 1},
  {answer_id: 4},
  {answer_id: 8},
  {answer_id: 9},
  {answer_id: 6},
  {answer_id: 11},
  {answer_id: 12},
  {answer_id: 13},
  {answer_id: 13},
  {answer_id: 17},
  {answer_id: 17},
  {answer_id: 17},
  {answer_id: 18},
  {answer_id: 18},
  {answer_id: 19},
  {answer_id: 19},
  {answer_id: 15},
  {answer_id: 14},
  {answer_id: 16},
  {answer_id: 16},
  {answer_id: 14},
  {answer_id: 15},
  {answer_id: 15},
  {answer_id: 15},
  {answer_id: 20},
  {answer_id: 20},
  {answer_id: 21},
  {answer_id: 22},
  {answer_id: 22},
  {answer_id: 21},
  {answer_id: 20},
  {answer_id: 20},
  {answer_id: 20},
  {answer_id: 20},
  {answer_id: 20},
  {answer_id: 20}
])
